swagger: '0.1'
info:
  description: 'This is the API for the Store'
  version: 0.0.2
  title: API Store
tags:
  - name: login
    description: To login in your account and acount settings and log out
  - name: manage products
    description: To delete or create product or change products
  - name: shopping
    description: To search and add Items to your shopping cart
schemes:
  - http
paths:
  /login:
    post:
      summary: 
      description: 'to login to your account'
      operationId: login
      consumes:
        - application/json
      produces:
        - application/json
      parameters:
        - in: body
          name: email
          description: The email for login
          required: true
        - in: body
          name: password
          description: The password for login
          required: true
      responses:
        '200':
          description: Login successful
        '405':
          description: wrong username or password
  /logout:
    get:
      summary: 
      description: 'to logout to your account'
      operationId: logout
      responses:   
        '200':
          description: logout successful
        '404':
          description: error

  /create_user:
    post:
      summary: 
      description: 'to create a user'
      operationId: create_user
      consumes:
        - application/json
      produces:
        - application/json
      parameters:
        - in: body
          name: email
          required: true
        - in: body
          name: password
          required: true
        - in: body
          name: username
          required: true
        - in: body
          name: geburtsdatum
          required: true
      responses:
        '200':
          description: user was created successfully
        '405':
          description: user already exist
  /update_user:
    put:
       summary:
       description: 'to update a user'
       operarionId: update_user
        consumes:
          - application/json
        produces:
          - application/json
        parameters:
          - in: body
            name: email
            require: true
                  - in: body
          name: password
          required: true
        - in: body
          name: username
          required: true
        - in: body
          name: geburtsdatum
          required: true
      responses:
      response:
        '200':
          description: user updated successfully
        '405':
          description: No changes

  /create_product:
    post:
      summary: 
        description: 'to create a product'
        operationId: create_product
        consumes:
          - application/json
        produces:
          - application/json
        parameters:
          - in: body
            name: name
            required: true
          - in: body
            name: price
            required: true
          - in: body
            name: Category
            required: true
          - in: body
            name: producer
            required: true
          - in: formData
            name: images
            required: true
        responses:
          '200':
            description: product was created successfully
          '405':
            description: product already exist
  /update_product:
    post:
      summary: 
        description: 'to update a product'
        operationId: update_product
        consumes:
          - application/json
        produces:
          - application/json
        parameters:
          - in: body
            name: name
            required: true
          - in: body
            name: price
            required: true
          - in: body
            name: Category
            required: true
          - in: body
            name: producer
            required: true
          - in: formData
            name: images
            required: true
        responses:
          '200':
            description: product was update successfully
          '405':
            description: no changes
